Hw2
Ivanuil/hw1_s2 pull request #3
Opened 2024-02-27 18:53 UTC by Ivanuil

2024-03-25 09:21 UTC, MaximKozlyuk requested changes

2024-03-25 09:21 UTC, MaximKozlyuk commented on src/main/java/edu/example/hw1_s2/service/MinioFileStorageService.java
> +        while (imageStorage.isObjectExist(generatedFileName)) {
это достаточно большой оверхед, да и вполне можно заложиться на то, что uuid всегда будет уникален. Чтобы быть точно уверенным - можно сделать разбиение файлов по папкам (путям) вида <год>/<месяц>/uuid.extension. Тогда вероятность коллизии совсем мала. А чтоб совсем железобетонно - навесь спринговый ретрай тут чтоб он еще 1 раз пытался в случае ошибки, не надо руками циклы наворачивать.

2024-03-25 09:21 UTC, MaximKozlyuk commented on src/main/java/edu/example/hw1_s2/service/MinioFileStorageService.java
> +        String generatedFileName = String.format("%s/%s", fileExt, UUID.randomUUID());
extension не всегда может существовать, можно заложить папку с отсутствующими extensions

2024-03-25 11:17 UTC, Ivanuil commented on src/main/java/edu/example/hw1_s2/service/MinioFileStorageService.java
> +        String generatedFileName = String.format("%s/%s", fileExt, UUID.randomUUID());
По идее до этой точки могут дойти только файлы с расширением из разрешенных, то есть гарантированно, что оно не нулевое
Но я добавил обработку пустых расширений, на случай если этот StorageService будет использован для сохранения других файлов

2024-04-07 19:26 UTC, MaximKozlyuk approved these changes

2024-04-07 19:36 UTC, merged